function TaxiHandler() {
    this.list = TaxiHandler.cities;
    this.init_();
};

TaxiHandler.prototype.init_ = function() {
    var temporaryList = [];

    this.list.forEach(function(city) {
        temporaryList.push(new Taxi(city));
    });

    this.list = temporaryList.slice(0, 3);
    delete temporaryList;
};

TaxiHandler.prototype.getAvailable = function() {
    return this.list;
};

TaxiHandler.prototype.setIdle = function(name) {
    var taxi = this.list.filter(function(item) {
        return item.address == name;
    });

    if (!taxi) return;

    this.list = this.list.filter(function(item) {
        return item.address != name;
    });
};

TaxiHandler.cities = [
         "Mexico City, Federal District Mexico"
        ,"Ecatepec de Morelos, State of Mexico Mexico"
        ,"Tijuana, Baja California Mexico"
        ,"Puebla, Puebla Mexico"
        ,"Guadalajara, Jalisco Mexico"
        ,"Leon, Guanajuato Mexico"
        ,"Ciudad Juarez, Chihuahua Mexico"
        ,"Zapopan, Jalisco Mexico"
        ,"Monterrey, Nuevo León Mexico"
        ,"Nezahualcóyotl, State of Mexico Mexico"
        ,"Mexicali, Baja California Mexico"
        ,"Culiacán, Sinaloa Mexico"
        ,"Naucalpan de Juárez, State of Mexico Mexico"
        ,"Mérida, Yucatan Mexico"
        ,"Toluca, State of Mexico Mexico"
        ,"Chihuahua, Chihuahua Mexico"
        ,"Querétaro, Querétaro Mexico"
        ,"Aguascalientes, Aguascalientes Mexico"
        ,"Acapulco, Guerrero Mexico"
        ,"Hermosillo, Sonora Mexico"
        ,"San Luis Potosí, San Luis Potosí Mexico"
        ,"Morelia, Michoacán Mexico"
        ,"Saltillo, Coahuila Mexico"
        ,"Guadalupe, Nuevo Leon Mexico"
        ,"Tlalnepantla de Baz, State of Mexico Mexico"
        ,"Cancun, Quintana Roo Mexico"
        ,"Villahermosa, Tabasco Mexico"
        ,"Torreón, Coahuila Mexico"
        ,"Chimalhuacán, State of Mexico Mexico"
        ,"Reynosa, Tamaulipas Mexico"
        ,"Tlaquepaque, Jalisco Mexico"
        ,"Durango, Durango Mexico"
        ,"Tuxtla Gutiérrez, Chiapas Mexico"
        ,"Veracruz, Veracruz Mexico"
        ,"Irapuato, Guanajuato Mexico"
        ,"Tultitlán, State of Mexico Mexico"
        ,"Apodaca, Nuevo León Mexico"
        ,"Atizapán de Zaragoza, State of Mexico Mexico"
        ,"Matamoros, Tamaulipas Mexico"
        ,"Tonalá, Jalisco Mexico"
        ,"Celaya, Guanajuato Mexico"
        ,"Ixtapaluca, State of Mexico Mexico"
        ,"Ensenada, Baja California Mexico"
        ,"Xalapa, Veracruz Mexico"
        ,"San Nicolás de los Garza, Nuevo Leon Mexico"
        ,"Mazatlán, Sinaloa Mexico"
        ,"Tlajomulco de Zúñiga, Jalisco Mexico"
        ,"Los Mochis, Sinaloa Mexico"
        ,"Ciudad Obregón, Sonora Mexico"
        ,"Nuevo Laredo, Tamaulipas Mexico"
        ,"Tepic, Nayarit Mexico"
        ,"Nicolás Romero, State of Mexico Mexico"
        ,"Cuernavaca, Morelos Mexico"
        ,"Tecámac, State of Mexico Mexico"
        ,"Valle de Chalco Solidaridad, State of Mexico Mexico"
        ,"General Escobedo, Nuevo Leon Mexico"
        ,"Gómez Palacio, Durango Mexico"
        ,"Ciudad Victoria, Tamaulipas Mexico"
        ,"Tapachula, Chiapas Mexico"
        ,"Uruapan, Michoacán Mexico"
        ,"Chalco, State of Mexico Mexico"
        ,"Coatzacoalcos, Veracruz Mexico"
        ,"Tampico, Tamaulipas Mexico"
        ,"Guasave, Sinaloa Mexico"
        ,"Coacalco de Berriozábal, State of Mexico Mexico"
        ,"Tehuacán, Puebla Mexico"
        ,"Santa Catarina, Nuevo León Mexico"
        ,"Soledad de Graciano Sánchez, San Luis Potosi Mexico"
        ,"Pachuca, Hidalgo Mexico"
        ,"Oaxaca, Oaxaca Mexico"
        ,"Salamanca, Guanajuato Mexico"
        ,"Campeche, Campeche Mexico"
        ,"Juarez, Nuevo Leon Mexico"
        ,"Puerto Vallarta, Jalisco Mexico"
        ,"Los Reyes Acaquilpan, State of Mexico Mexico"
        ,"La Paz, Baja California Sur Mexico"
        ,"Cardenas, Tabasco Mexico"
        ,"Chetumal, Quintana Roo Mexico"
        ,"Huixquilucan, State of Mexico Mexico"
        ,"San Juan del Rio, Queretaro Mexico"
        ,"Chilpancingo, Guerrero Mexico"
        ,"Los Cabos, Baja California Sur Mexico"
        ,"Texcoco, State of Mexico Mexico"
        ,"Ciudad del Carmen, State of Mexico Mexico"
        ,"Nogales, Sonora Mexico"
        ,"Monclova, Coahuila Mexico"
        ,"Metepec, State of Mexico Mexico"
        ,"Fresnillo, Zacatecas Mexico"
        ,"Altamira, Tamaulipas Mexico"
        ,"Ocosingo, Chiapas Mexico"
        ,"Ciudad Madero, Tamaulipas Mexico"
        ,"Jiutepec, Morelos Mexico"
        ,"Córdoba, Veracruz Mexico"
        ,"Poza Rica, Veracruz Mexico"
        ,"Comalcalco, Tabasco Mexico"
        ,"Chicoloapan, State of Mexico Mexico"
        ,"San Cristobal de las Casas, Chiapas Mexico"
        ,"Zamora, Michoacán Mexico"
        ,"Huimanguillo, Tabasco Mexico"
        ,"San Luis Rio Colorado, Sonora Mexico"
        ,"Lázaro Cárdenas, Michoacán Mexico"
        ,"Cuautla, Morelos Mexico"
        ,"Silao, Guanajuato Mexico"
        ,"Guanajuato, Guanajuato Mexico"
        ,"Ciudad Valles, San Luis Potosi Mexico"
        ,"Zinacantepec, State of Mexico Mexico"
        ,"Manzanillo, Colima Mexico"
        ,"San Miguel de Allende, Guanajuato Mexico"
        ,"Manzanillo, Colima Mexico"
        ,"Minatitlán, Veracruz Mexico"
        ,"Macuspana, Tabasco Mexico"
        ,"Zinacantepec, State of Mexico Mexico"
        ,"Navojoa, Sonora Mexico"
        ,"San Juan Bautista Tuxtepec, Oaxaca Mexico"
        ,"Boca del Río, Veracruz Mexico"
        ,"Zumpango, State of Mexico Mexico"
        ,"Guadalupe, Zacatecas Mexico"
        ,"Papantla, Veracruz Mexico"
        ,"Lerdo, Durango Mexico"
        ,"Lagos de Moreno, Jalisco Mexico"
        ,"Tuxpan, Veracruz Mexico"
        ,"Allende, Guanajuato Mexico"
        ,"Cuautitlán Izcalli, State of Mexico Mexico"
        ,"Almoloya de Juárez, State of Mexico Mexico"
        ,"Zacatecas, Zacatecas Mexico"
        ,"San Martín Texmelucan, Puebla Mexico"
        ,"Cuauhtémoc, Chihuahua Mexico"
        ,"Zitácuaro, Michoacán Mexico"
        ,"Tepatitlán, Jalisco Mexico"
        ,"Ixtlahuaca de Rayón, State of Mexico Mexico"
        ,"Guaymas, Sonora Mexico"
        ,"Cuautitlán, State of Mexico Mexico"
        ,"Acuña, Coahuila Mexico"
        ,"Colima, Colima Mexico"
        ,"Dolores Hidalgo, Guanajuato Mexico"
        ,"Pénjamo, Guanajuato Mexico"
        ,"Tulancingo, Hidalgo Mexico"
        ,"Delicias, Chihuahua Mexico"
        ,"El Salto, Jalisco Mexico"
        ,"Navolato, Sinaloa Mexico"
        ,"Comitán, Chiapas Mexico"
        ,"Huejutla de Reyes, Hidalgo Mexico"
        ,"Corregidora, Querétaro Mexico"
        ,"Iguala, Guerrero Mexico"
        ,"Valle de Santiago, Guanajuato Mexico"
        ,"Tultepec, State of Mexico Mexico"
        ,"San Pedro Cholula, Puebla Mexico"
        ,"Chilapa de Álvarez, Guerrero Mexico"
        ,"Atlixco, Puebla Mexico"
        ,"San Pedro Garza García, Nuevo León Mexico"
        ,"Orizaba, Veracruz Mexico"
        ,"Villa de Álvarez, Colima Mexico"
        ,"Cunduacán, Tabasco Mexico"
        ,"Apatzingán, Michoacán Mexico"
        ,"Lerma, State of Mexico Mexico"
        ,"Cosoleacaque, Veracruz Mexico"
        ,"Ciudad Hidalgo, Michoacán Mexico"
        ,"Chilón, Chiapas Mexico"
        ,"El Mante, Tamaulipas Mexico"
        ,"Río Bravo, Tamaulipas Mexico"
        ,"Palenque, Chiapas Mexico"
        ,"José Azueta, Guerrero Mexico"
        ,"San Francisco del Rincón, Guanajuato Mexico"
        ,"Tecate, Baja California Mexico"
        ,"Temixco, Morelos Mexico"
        ,"Parral, Chihuahua Mexico"
        ,"Matamoros, Coahuila Mexico"
        ,"Tantoyuca, Veracruz Mexico"
        ,"Las Margaritas, Chiapas Mexico"
        ,"Temapache, Veracruz Mexico"
        ,"San Luis de la Paz, Guanajuato Mexico"
        ,"Ciudad Guzmán, Jalisco Mexico"
        ,"Martínez de la Torre, Veracruz Mexico"
    ];